
import { Translation } from './types';

export const TRANSLATIONS: Record<'en' | 'zh', Translation> = {
  en: {
    title: 'Binance Monitor',
    spot: 'Spot',
    futures: 'Futures',
    price: 'Price',
    change: '24h Change',
    volume: '24h Volume',
    alerts: 'Volatility Alerts',
    alert_volume: 'Volume Spike (+30%)',
    alert_surge: 'Price Surge (+10%)',
    alert_dump: 'Price Dump (-10%)',
    loading: 'Loading market data...',
    search_placeholder: 'Search Coin...',
    time_1m: '1m',
    time_5m: '5m',
    time_15m: '15m',
    monitor_active: 'Monitoring Top Assets',
    no_alerts: 'No recent anomalies detected.',
    order_book: 'Order Book',
    recent_trades: 'Recent Trades',
    amount: 'Amount',
    total: 'Total',
    time: 'Time',
    sort_volume: 'Vol',
    sort_gainers: 'Risers',
    sort_losers: 'Fallers',
    nav_market: 'Market Monitor',
    nav_arbitrage: 'Arbitrage',
    nav_feargreed: 'Fear & Greed',
    pos_rate: 'Positive Fee Rate (Long Spot / Short Futures)',
    neg_rate: 'Negative Fee Rate (Short Spot / Long Futures)',
    funding_rate: 'Rate',
    apr: 'APR (Yearly)',
    spread: 'Spread',
    next_settle: 'Next Settle',
    refresh: 'Refresh',
    fear_greed_title: 'Crypto Fear & Greed Index',
    fg_now: 'Current Sentiment',
    fg_history: 'Historical Trend (Last 30 Days)',
    next_update: 'Next Update In',
    cex_dex_title: 'CEX/DEX Arbitrage (Mock)',
    binance_price: 'Binance',
    aster_price: 'Aster DEX',
    hype_price: 'Hype Swap',
    route: 'Best Route',
    profit: 'Est. Profit',
  },
  zh: {
    title: '币安监控面板',
    spot: '现货',
    futures: '合约',
    price: '当前价格',
    change: '24h 涨跌',
    volume: '24h 成交量',
    alerts: '异动警报',
    alert_volume: '成交量放大 (+30%)',
    alert_surge: '价格暴涨 (+10%)',
    alert_dump: '价格暴跌 (-10%)',
    loading: '正在加载市场数据...',
    search_placeholder: '搜索全币种...',
    time_1m: '1分',
    time_5m: '5分',
    time_15m: '15分',
    monitor_active: '正在监控主流资产',
    no_alerts: '暂无异常波动',
    order_book: '订单薄',
    recent_trades: '最近成交',
    amount: '数量',
    total: '总额',
    time: '时间',
    sort_volume: '交易量',
    sort_gainers: '涨幅榜',
    sort_losers: '跌幅榜',
    nav_market: '行情监控',
    nav_arbitrage: '资金费套利',
    nav_feargreed: '恐慌贪婪',
    pos_rate: '正费率 (买现货/做空合约)',
    neg_rate: '负费率 (卖现货/做多合约)',
    funding_rate: '资金费率',
    apr: '年化收益',
    spread: '期现价差',
    next_settle: '下次结算',
    refresh: '刷新数据',
    fear_greed_title: '加密货币恐慌与贪婪指数',
    fg_now: '当前市场情绪',
    fg_history: '历史情绪趋势 (近30天)',
    next_update: '下次更新',
    cex_dex_title: 'CEX/DEX 套利 (模拟)',
    binance_price: '币安价格',
    aster_price: 'Aster DEX',
    hype_price: 'Hype Swap',
    route: '最佳路径',
    profit: '预估利润',
  }
};

// Base host only, endpoints are appended in service/components
export const WS_BASE_SPOT = 'wss://stream.binance.com:9443';
export const WS_BASE_FUTURES = 'wss://fstream.binance.com';

export const API_BASE_SPOT = 'https://api.binance.com/api/v3';
export const API_BASE_FUTURES = 'https://fapi.binance.com/fapi/v1';